### ISSUE TITLE
閲覧権限の無いチケットが「かんばん」で見れてしまう

### ISSUE THREAD

**Issue by zulunine** [ayapapa/redmine_backlogs#17]
閲覧権限の無い他のユーザーのプライベート設定のチケットが、「かんばん」上で表示され内容も見れてしまいます。
チケット一覧では該当の閲覧権限の無いチケットは表示されません。

**Comment by ayapapa** [comment]
@zulunine さん、
issue登録有難うございます。時間がかかるかもしれませんが、調べてみます。  
また、何かヒントのような物を @zulunine さんが見つけましたら、お知らせいただけますと助かります。

**Comment by ayapapa** [comment]
@zulunine さん、
原因らしきものが分かったので、対策をredmine3ブランチにコミット(19076b1)してみました。手元では、想定通り動いています。ご確認をお願いいたします。

**Comment by ayapapa** [comment]
3か月たっため、クローズします。
もし、期待通りの動作になっていないことが分かりましたら、再度オープンします。
