### ISSUE TITLE
かんばんからNew Taskを作成すると404になる

### ISSUE THREAD

**Issue by yoshi-h** [ayapapa/redmine_backlogs#21]
バージョン４対応ありがとうございます。
下記の環境でpluginを導入することはできたのですが、かんばんからNew Taskを発行しようとするとNew Taskのダイアログが404エラーとなります。
原因や対処方法等分かればご教示ください。

CentOS Linux release 7.6.1810
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.6.1-p33 (2019-01-30) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_backlogs               v1.0.6

**Comment by phongaster** [comment]
apps/redmine/htdocs/app/models/issue.rb:439
`#attrs.stringify_keys!`
のようにコメントアウトすれば解決できます。

**Comment by phongaster** [comment]
原因は、渡されるパラメーターがハッシュではない場合に `NoMethodError` が発生してしまいます。
[rb_tasks_controller.rb.txt](https://github.com/ayapapa/redmine_backlogs/files/6097329/rb_tasks_controller.rb.txt)

**Comment by ayapapa** [comment]
長らく放置してしまいました。すいません。

少し時間に余裕が出てきましたので、活動を再開しております。
時すでに遅しでしたら、申し訳ありません。

本問題につきましては、別の方の対応を参考（マージ, #22）して、対応しました。redmine4ブランチに反映してみました。
ただ、一部エラー表示等、手直しが必要そうなところが、まだありそうですので、別issueを登録して対応する予定です。

以上、よろしくお願いします。
